# installCRDs: true
# namespace:
#   create: true
#   name: cert-manager
#   labels:
#     cert-manager.io/disable-validation: true

nodeSelector:  
  "app": system-apps
webhook:
  nodeSelector:
    "app": system-apps
cainjector:
  nodeSelector:
    "app": system-apps