apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-claim
  name: postgres-claim
  namespace: {{ include "ahi-chart.namespace" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
