apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ include "ahi-chart.namespace" . }}
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
  PGDATA: /var/lib/postgresql/data/pgdata