apiVersion: v1
kind: Secret
metadata:
  name: cosmos-db-secret
  namespace: {{ include "ahi-chart.namespace" . }}
type: Opaque
data:
  database: {{.Values.ahi.api.dataSource.database }}
  key: {{.Values.ahi.api.dataSource.key}}
  uri: {{.Values.ahi.api.dataSource.uri}}