apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  namespace: {{ include "ahi-chart.namespace" . }}
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image:  {{ .Values.ahi.eureka.image }}
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
          resources:
            requests:
              memory: {{.Values.ahi.eureka.memory }}
      nodeSelector:
        app: system-apps